services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: tunnel
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env
    environment:
      TUNNEL_TRANSPORT_PROTOCOL: http2
    network_mode: host