services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    restart: always
    volumes:
      - /home/ansible-user/database/postgresql_data:/var/lib/postgresql
      - /home/ansible-user/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - traefik
    ports:
      - 5432:5432
    env_file: .env
    labels:
      - "traefik.enable=true"        
      - "traefik.tcp.routers.postgres.entrypoints=tcp"      
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"                             
      - "traefik.tcp.routers.postgres.tls=false"     
      - "traefik.tcp.routers.postgres.service=postgres"  
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    user: "0:0"
    ports:
      - "8888:8888"
    env_file: .env
    networks:
      - traefik
    volumes:
      - /home/ansible-user/database/pgadmin-data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.eq-01.pi.hole`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.service=pgadmin"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=8888"

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.eq-01.pi.hole`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.service=adminer"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true