services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "9556:8080"
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
    volumes:
      - /home/ansible-user/ollama/open-webui:/app/backend/data
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=Host(`chat.eq-01.pi.hole`)"
      - "traefik.http.routers.chat.entrypoints=websecure"
      - "traefik.http.routers.chat.service=chat"
      - "traefik.http.services.chat.loadbalancer.server.port=8080"

  ollama:
    image: ollama/ollama:0.12.6
    container_name: ollama
    ports:
      - "9555:11434"
    volumes:
      - /home/ansible-user/ollama/ollama_volume:/root/.ollama
      - /home/ansible-user/ollama/entrypoint.sh:/entrypoint.sh
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=Host(`ollama.eq-01.pi.hole`)"
      - "traefik.http.routers.ollama.entrypoints=websecure"
      - "traefik.http.routers.ollama.service=ollama"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

networks:
  traefik:
    external: true