services:
  grafana:
    image: grafana/grafana-oss
    user: "0"
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - /home/ansible-user/lnm/grafana:/var/lib/grafana
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.eq-01.pi.hole`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls.certresolver=localtlschallenge"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true