services:
  download-emails:
    container_name: download-emails
    build:
      context: .
      no_cache: yes
    environment:
      - START_DATE=${START_DATE}
      - END_DATE=${END_DATE}
      - PAGES_TO_PROCESS=${PAGES_TO_PROCESS}
    volumes:
      - '/home/ansible-user/scripts/categorize-gmail/secrets:/config'
      - '/home/ansible-user/scripts/categorize-gmail/data:/data'