tls:
  certificates:
    - certFile: "/conf/certs/tls.crt"
      keyFile: "/conf/certs/tls.key"
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      sniStrict: true