services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-runner
    restart: unless-stopped
    env_file:
      - /home/ansible-user/github-runner/home/secrets/.env
    volumes:
      - /home/ansible-user/github-runner/home:/home/github-runner
    networks:
      - traefik

networks:
  traefik:
    external: true