version: "3"
services:
  portainer:
    image: portainer/portainer-ce:2.21.1
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ansible-user/portainer/secrets/:/certs
    restart: always
    command:
      --sslcert /certs/tls.crt
      --sslkey /certs/tls.key
volumes:
  portainer_data: