version: "3"
services:
  portainer:
    image: portainer/portainer-ce:2.29.0
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ansible-user/portainer/secrets/:/certs
    restart: always
    command:
      --sslcert /certs/tls.crt
      --sslkey /certs/tls.key
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.eq-01.pi.hole`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  traefik:
    external: true

volumes:
  portainer_data: