---
- name: Setup Homelab
  hosts: controllers
  remote_user: ansible-user
  become: yes
  roles:
    - firewall
    # - docker
    - traefik
    # - n8n
    # - portainer
    # - lnm
    # - filebrowser
    # - pihole
    # - cron
    # - ollama
    - homepage