---
- name: Setup Homelab
  hosts: controllers
  remote_user: ansible-user
  become: yes
  roles:
    - role: firewall
      tags:
      - firewall
    - role: docker
      tags:
      - docker
    - role: traefik
      tags:
      - traefik
    - role: portainer
      tags:
      - portainer
    - role: pihole
      tags:
      - pihole
    - role: filebrowser
      tags:
      - filebrowser
    - role: database
      tags:
      - database
    - role: lnm
      tags:
      - lnm
    - role: n8n
      tags:
      - n8n
    - role: scripts
      tags:
      - scripts
    - role: ollama
      tags:
      - ollama
    - role: homepage
      tags:
      - homepage
    - role: github-runner
      tags:
        - github-runner
    - role: gemini-cli
      tags:
        - gemini-cli
    - role: tunnel
      tags:
        - tunnel