---
- name: Setup Homelab
  hosts: controllers
  remote_user: ansible-user
  become: yes
  roles:
    - firewall
    - docker
    - portainer
    - lnm
    - filebrowser
    - pihole
    - cron
    - ollama