services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    env_file:
      - .env
    command:
      - start-dev
    environment:
      KC_HTTP_PORT: 8080
      # KC_IMPORT: /opt/keycloak/data/import/myrealm.json
    ports:
      - "9221:8080"
    networks:
      - traefik
    volumes:
      - "/home/ansible-user/keycloak/data:/opt/keycloak/data"

networks:
  traefik:
    external: true