services:
  nginx-proxy:
    image: nginx:1.27.0-alpine-slim
    container_name: nginx-proxy
    volumes:
      - "/home/ansible-user/nginx-proxy/conf.d:/etc/nginx/conf.d/"
      - "/home/ansible-user/nginx-proxy/ssl:/var/secure/"
    ports:
      - "80:80"
      - "443:443"