services:
  gemini-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-cli
    env_file:
      - .env
    volumes:
      - /home/ansible-user/gemini-cli/app:/app
    networks:
      - traefik

networks:
  traefik:
    external: true