- name: Copy nginx-proxy files in
  copy: 
    src: nginx-proxy/{{ item }}
    dest: /home/ansible-user/nginx-proxy/
  loop:
    - docker-compose.yml
  
- name: Create directories
  ansible.builtin.file:
    path: /home/ansible-user/nginx-proxy/{{ item }}
    state: directory
  ignore_errors: yes
  loop:
    - conf.d
    - ssl

- name: Copy ssl cert and key files in
  copy: 
    src: nginx-proxy/secrets/{{ item }}
    dest: /home/ansible-user/nginx-proxy/ssl
  loop:
    - eq-01.pi.hole.crt
    - eq-01.pi.hole.key

- name: Copy nginx-proxy conf files in
  copy: 
    src: nginx-proxy/{{ item }}
    dest: /home/ansible-user/nginx-proxy/conf.d
  loop:
    - default.conf

- name: Remove nginx-proxy
  shell: cd nginx-proxy && docker compose down && docker compose rm
  ignore_errors: yes

- name: Setup nginx-proxy
  shell: cd nginx-proxy && docker compose up -d